# name: 'frontend/*'
on:
  push:
    paths:
      - 'frontend/**'

jobs:
   CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with: 
          ref: 'workflows'
          fetch-depth: 0

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy html to S3
        run: aws s3 sync frontend/templates s3://${{ secrets.AWS_S3_BUCKET_NAME }}/

      - name: Deploy json to S3
        run: aws s3 cp frontend/config.json s3://${{ secrets.AWS_S3_BUCKET_NAME }}/

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
